### ISSUE TITLE
worker cannot connect to other worker for data transmission

### ISSUE THREAD

**Issue by typhoonzero** [typhoonzero/storm-docker#1]
after submit topology, seeing error in woker-6700.log:

```
2016-06-02T08:42:10.281+0000 b.s.m.n.StormClientErrorHandler [INFO] Connection failed Netty-Client-storm-worker-controller-ayzbi:6700
java.nio.channels.UnresolvedAddressException: null
    at sun.nio.ch.Net.checkAddress(Net.java:101) ~[na:1.8.0_91]
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622) ~[na:1.8.0_91]
    at org.apache.storm.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.channel.Channels.connect(Channels.java:634) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.channel.AbstractChannel.connect(AbstractChannel.java:207) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229) [storm-core-0.9.3.jar:0.9.3]
    at org.apache.storm.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182) [storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.messaging.netty.Client.connect(Client.java:152) [storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.messaging.netty.Client.access$000(Client.java:43) [storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.messaging.netty.Client$1.run(Client.java:107) [storm-core-0.9.3.jar:0.9.3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_91]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

**Comment by typhoonzero** [comment]
I'm trying to adding Pod to dns resolve. does some one know that is someone already working on this?

**Comment by typhoonzero** [comment]
use storm.local.hostname, so no need to add pod names to DNS.
by the way, pod names may be the same to service names, that's still problem to solve.
